# Generated by Django 5.0.3 on 2024-03-20 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("number_of_cats", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Cat",
            fields=[
                ("cat_id", models.AutoField(primary_key=True, serialize=False)),
                ("cat_name", models.CharField(max_length=100)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cats",
                        to="mainsite.student",
                    ),
                ),
            ],
        ),
    ]
